Add new restricted view alert to docs
blackbaud/stache2-docs pull request #198
Opened 2021-01-21 16:06 UTC by blackbaud-johnly

2021-01-21 16:18 UTC, blackbaud-ado commented
Preview build at [https://host.nxt.blackbaud.com/stache?_sp.spa=pr-restricted-view-alert](https://host.nxt.blackbaud.com/stache?_sp.spa=pr-restricted-view-alert)

2021-01-21 16:35 UTC, Blackbaud-LindseyRix commented
There are a few places in these docs that we use the restricted view, should we also add this alert to that area?

2021-01-21 18:12 UTC, Blackbaud-TrevorBurch requested changes
@blackbaud-johnly - one question from my point of view.

2021-01-21 18:12 UTC, Blackbaud-TrevorBurch commented on src/app/components/restricted-view/index.html
> +        <sky-code>sky-restricted-content-alert</sky-code> — The <sky-code>sky-restricted-content-alert</sky-code> component displays an <a routerLink="/components/alerts">alert</a> that instructs use
Technically the user has to be a Blackbaud employee who logged in with BBID and now isn't for this to show up. It does not show up if a user previously logged in with a non-employee BBID.

2021-01-21 19:30 UTC, blackbaud-johnly commented
> There are a few places in these docs that we use the restricted view, should we also add this alert to that area?

@Blackbaud-LindseyRix, I added the alert to the search docs, which is the only other place I saw where we had restricted view in place. Feel free to update with any others that you know of. ... Also, can you please peer review this PR? Thanks in advance.

2021-01-21 19:31 UTC, blackbaud-johnly commented on src/app/components/restricted-view/index.html
> +        <sky-code>sky-restricted-content-alert</sky-code> — The <sky-code>sky-restricted-content-alert</sky-code> component displays an <a routerLink="/components/alerts">alert</a> that instructs use
Updated. Thanks!

2021-01-21 19:37 UTC, Blackbaud-TrevorBurch approved these changes

2021-01-21 19:39 UTC, blackbaud-ado commented
Preview build at [https://host.nxt.blackbaud.com/stache?_sp.spa=pr-restricted-view-alert](https://host.nxt.blackbaud.com/stache?_sp.spa=pr-restricted-view-alert)

2021-01-22 00:49 UTC, blackbaud-ellynhassell approved these changes

2021-01-22 14:36 UTC, Blackbaud-LindseyRix approved these changes

2021-01-22 15:00 UTC, merged